version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/
    ports:
      - 8000:80
  db:
    platform: linux/x86_64
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3305:3305
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: khong
      MYSQL_USER: khong
      MYSQL_PASSWORD: khongpass 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
